SELECT name FROM `products`;
SELECT name, price FROM `products`;     
SELECT name FROM `products` WHERE price <= 200;
SELECT * FROM `products` WHERE price <= 120 AND price >=60;
SELECT name, price * 100 FROM `products`;
SELECT AVG(price) FROM `products`;
SELECT AVG(price) FROM `products`WHERE manufacturer = 46;
SELECT COUNT(*) FROM `products`WHERE price >= 180;
SELECT name, price FROM `products` WHERE price >= 180 ORDER BY price DESC, name ASC;
SELECT * FROM `products` JOIN manufactures ON products.manufacturer=manufactures.id;
SELECT products.name, products.price, manufactures.name FROM `products` JOIN manufactures ON products.manufacturer=manufactures.id;
SELECT manufacturer, AVG(price) FROM `products` GROUP BY manufacturer;
SELECT manufactures.name, AVG(products.price) FROM `products` JOIN manufactures ON products.manufacturer=manufactures.id GROUP BY manufacturer;
SELECT name, min(price) FROM `products`;
INSERT INTO `products` (name, price, manufacturer) VALUES ("Luidsprekers", 70, 2);
UPDATE `products` SET name="Laser Printer" WHERE id=8;
UPDATE `products` SET price=price*0.9;
UPDATE `products` SET price=price*0.9 WHERE price >= 120;